version: '3.4'

services:
  catalogdb.srv:
    container_name: catalogdb.name
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db

  catalog.api.srv:
    container_name: catalog.api.name
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb.name:27017"
    depends_on:
      - catalogdb.srv
    ports:
      - "8000:80"

  shop.api.srv:
    container_name: shop.api.name
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "80"
      - "8001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro
